### ISSUE TITLE
Verbose output

### ISSUE THREAD

**Issue by Dooez** [lawmurray/doxide#22]
Having an option for verbose output could be helpful, for example outputting the line that caused the parse error.
I am encountering a lot of parse errors and would like to know if i can adjust my code to reduce them.

**Comment by lawmurray** [comment]
Thanks for the suggestion @Dooez.

If it's useful in the meantime, most parse errors come from macro use, for example macros that define function attributes:

```cpp
#define NOINLINE [[noinline]]

NOINLINE int f(int x);
```
Because Doxide (well, [tree-sitter](https://tree-sitter.github.io/tree-sitter/)) does not run a preprocessor, this can look like a syntax error in the declaration of `f`. In my experience, despite the warnings, it is managing to extract the right entities and their documentation nonetheless.

**Comment by lawmurray** [comment]
@Dooez FYI the new v0.4.0 provides much more useful output on parse errors, including line and column numbers. For parse errors related to macro use, there is also new error recovery logic and the ability to define macros in the configuration file (see [documentation](https://doxide.org/parsing)).

I'll close the issue as completed now, but feel free to reply or reopen, or post any followup issues that you encounter.
